apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: assisted-service-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assisted-service-operator
  namespace: system
  labels:
    control-plane: assisted-service-operator
spec:
  selector:
    matchLabels:
      control-plane: assisted-service-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: assisted-service-operator
    spec:
      containers:
      - command:
        - /assisted-service-operator
        args:
        - --leader-elect
        image: quay.io/ocpmetal/assisted-service:latest
        name: manager
        env:
          - name: SERVICE_IMAGE
            value: quay.io/ocpmetal/assisted-service:latest
          - name: DATABASE_IMAGE
            value: quay.io/ocpmetal/postgresql-12-centos7:latest
          - name: AGENT_IMAGE
            value: quay.io/ocpmetal/assisted-installer-agent:latest
          - name: CONTROLLER_IMAGE
            value: quay.io/ocpmetal/assisted-installer-controller:latest
          - name: INSTALLER_IMAGE
            value: quay.io/ocpmetal/assisted-installer:latest
          - name: OPENSHIFT_VERSIONS
            value: '{"4.6":{"display_name":"4.6.16","release_image":"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rhcos_version":"46.82.202012051820-0","support_level":"production"},"4.7":{"display_name":"4.7.5","release_image":"quay.io/openshift-release-dev/ocp-release:4.7.5-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso","rhcos_version":"47.83.202102090044-0","support_level":"production"}}'
          - name: SERVICE_ACCOUNT_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
